#!/bin/bash

RUN_DIR=/var/vcap/sys/run/timer_runner
LOG_DIR=/var/vcap/sys/log/timer_runner

PIDFILE=$RUN_DIR/timer_runner.pid
RUNAS=vcap

#export GOROOT=/var/vcap/packages/golang
export GOROOT=<%= p('goroot') %>
#export PATH=$GOROOT/bin:$PATH

function pid_exists() {
  ps -p $1 &> /dev/null
}

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    exec chpst -u $RUNAS:$RUNAS \
      <%= p('timer_exe_name') %> \
      >>$LOG_DIR/server.stdout.log 2>>$LOG_DIR/server.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    if [ ! -z $PID ] && pid_exists $PID; then
      kill $PID
    fi
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: ctl {start|stop}" ;;
esac
exit 0
